# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 800c265f7130004077b58c2361984f74c2004bc0d50ce0dba7778509136646275205f0a509f5aa483a633178fb350216b812580ba420f131349eb8dd325634ae

test:
  secret_key_base: e04d7682a00e59a0971807311d737a2c9e0ce270a8162119a30b1facb11f55e8b46cdbef369d498a4c47f8a28e758d836c5c18694398743530c55d5de71aa82e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
